indico/newdle

.gitignore, conftest.py, newdle/api.py, newdle/core/app.py, newdle/core/util.py, newdle/models.py, newdle/schemas.py, pytest.ini, requirements.dev.txt, requirements.txt, tests/models_test.py
This closes #19 and #22 and adds as well the possibility to create Python unit tests.
When it comes to testing, you should have an empty `newdle_tests` DB in your machine. It would be great if we could reuse https://github.com/indico/indico/blob/master/indico/testing/fixtures/database.py and https://github.com/indico/indico/blob/master/indico/core/db/sqlalchemy/util/management.py, maybe moving them to a 3rd party lib?
=> Add DB models and tests, POST for newdle creation

newdle/client/src/actions.js, newdle/client/src/components/CreateNewdle.js, newdle/client/src/components/UnloadPrompt.js, newdle/client/src/reducers.js, newdle/client/src/selectors.js
Navigating away from the Newdle creation page now resets all creation-related data in the state. If the user made any meaningful changes (anything except duration for now), they are also prompted to confirm before navigating away.
closes #52
=> Reset creation state when leaving /new & prompt before losing data

newdle/client/src/actions.js, newdle/client/src/auth.js, newdle/client/src/client.js, newdle/client/src/components/App.js, newdle/client/src/components/LoginPrompt.js, newdle/client/src/reducers.js, newdle/client/src/selectors.js
When not logged-in, a slightly different modal is shown
=> Fix token refresh for concurrent requests & requests where no token is present

newdle/client/src/components/CreateNewdle.js, newdle/client/src/components/Home.js, newdle/client/src/components/Navigator.js, newdle/client/src/components/Navigator.module.scss
The "back" buttons now look nicer:
The `Navigator` was also improved. The steps are now clickable:
Closes #64
=> Make "back" buttons nicer

newdle/client/package-lock.json, newdle/client/package.json, newdle/client/src/components/AvailabilityRing.js, newdle/client/src/components/ParticipantTable.js, newdle/client/src/selectors.js
Replaced `react-circular-progressbar` with AvailabilityRing.js, a component that returns an svg and a counter to show meeting participant status.
AvailabilityRing.js support 3 states (Red, Yellow, Green) and displays a counter (below the ring) for the number of `accepted invitations / total invitations`.
Props include: 
-  available: number of people available
- ifNeeded: number of people available if needed
- totalParticipants: number of people invited
- strokeWidth: width of stroke (optional)
- radius: radius of ring (optional)
Example States:
Definitely open to feedback :)
closes #151
=> Use nicer availability ring in summary

newdle/api.py, newdle/client/src/actions.js, newdle/client/src/answerSelectors.js, newdle/client/src/client.js, newdle/client/src/components/answer/AnswerPage.js, newdle/client/src/components/creation/timeslots/Availability.js, newdle/client/src/components/creation/timeslots/Timeline.js, newdle/client/src/reducers/creation.js, newdle/providers/free_busy/exchange.py, newdle/providers/free_busy/random.py
* This PR makes it so that the free/busy views take into account the current timezone the user is in.
* This means as well that, during the creation of the newdle, updates in the timezone field will result in the free/busy information being fetched again.
* I have also fixed the handling of free/busy dates that fall outside the visible hour range.
* In what concerns the Exchange part, I have made sure we operate using the account's timezone and then properly calculate the overlaps based on the newdle's timezone;
=> Fix the handling of timezones in free/busy views

newdle/client/src/components/summary/SummaryHeader.js, newdle/client/src/selectors.js
While only the creator can view the summary right now, this will eventually change and even right now the "broken" view when trying to view someone else's newdle shows the wrong name.
Also removed some selectors that aren't very useful since those values can be easily retrieved from the newdle object itself.
=> Use actual newdle creator_name in summary header

conftest.py, newdle/api.py, newdle/client/src/actions.js, newdle/client/src/client.js, tests/api_test.py
This way we don't end up with a half-broken page when trying to view a Newdle we can't access.
The error display is still not amazing (403 error message from the failed API call) though. Ideally we;d check whether the user is the newdle's creator and if not either show a more user-friendly message or a simplified version (using just the public information that's available)
closes #157
=> Use separate endpoint to get participant list

Makefile, package.json
Update the lint step to check the code style without applying any changes.
Also, lock the prettier version to 1.18 to prevent 1.19 new function literal heuristic (refer to prettier's #6921).
Closes #172
=> Add the missing lint scripts

tests/api_test.py
Add some of the missing tests in 'api_test.py' (#160):
- add test for create_participant
- create_unknown_participant
- get_participant_me
- update_newdle
- get_my_newdles
=> Add python tests for api.py

conftest.py, newdle/api.py, newdle/client/src/client.js, newdle/client/src/components/App.js, newdle/client/src/components/MyNewdles.js, newdle/client/src/components/NewdlesImIn.js, newdle/client/src/components/NewdlesParticipating.js, newdle/client/src/components/UserMenu.js, newdle/models.py, newdle/schemas.py, tests/api_test.py
Closes #164 
Some notes:
- Should "expired" newdles, i.e., with final date set be excluded?
- This PR doesn't change any of the page styles, should we add something to distinguish the two pages? A title such as "The newdles you are part of" and "The newdles you created", or merging the two together in the same page.
- A suggestion for an interesting feature would be, replacing the placeholder "x out of X participants answered" with something like "You chose the '2019-09-11T13:00' slot" or "You chose 3 slots", for the newdles-im-in page, since you can't see the participants.
=> Add "newdles I'm in" page to user profile

newdle/cern_integration.py
Do not merge this until the API actually returns real emails there and it's confirmed that our app id has access to it.
=> Use real emails for CERN accounts

newdle/client/src/components/creation/timeslots/Timeline.js, newdle/client/src/components/creation/timeslots/Timeline.module.scss, newdle/client/src/selectors.js, newdle/client/src/util/date.js
Default time for timeslots will now be either the end of the previous one or the first unused one of the previous date, depending on whether there are timeslots on the current day already.
Closes #188.
=> Make default time for timeslots smarter

conftest.py, newdle/api.py, newdle/client/src/actions.js, newdle/client/src/client.js, newdle/client/src/components/NewdleTitle.js, newdle/client/src/components/NewdleTitle.module.scss, newdle/client/src/components/ParticipantTable.js, newdle/client/src/components/answer/AnswerHeader.js, newdle/client/src/components/answer/AnswerPage.js, newdle/client/src/components/creation/FinalStep.js, newdle/client/src/components/creation/creation.module.scss, newdle/client/src/components/summary/SummaryHeader.js, newdle/client/src/components/summary/SummaryPage.js, newdle/client/src/reducers/creation.js, newdle/client/src/selectors.js, newdle/migrations/versions/20200814_1707_93a638b96375_add_private_column_to_newdle_model.py, newdle/models.py, newdle/schemas.py, tests/api_test.py
Participants can now look at the summary of newdles (to see how others have voted) if it is set to public by the creator.
For already existing newdles it is still set to private, however.
Closes #174.
=> Add option to make newdle summary public/private

newdle/client/src/actions.js, newdle/client/src/answerSelectors.js, newdle/client/src/components/MyNewdles.js, newdle/client/src/components/NewdleTitle.js, newdle/client/src/components/answer/AnswerPage.js, newdle/client/src/reducers/answer.js
This is important when not logged in or viewing another participant, since otherwise going to the summary and back (using the button in newdle, not the browser's back button) would result in an empty participant code and thus your old answer not being displayed anymore.
=> Preserve participant code when switching views

newdle/core/util.py, newdle/providers/free_busy/exchange.py, newdle/providers/free_busy/random.py
Previously the random times were the same regardless of timezone, which is confusing when testing anything timezone-related. Now we have the same timezone logic as used for the real data from exchange.
=> Correctly handle timezones in random free-busy

newdle/auth.py, newdle/core/app.py
This PR fixes two problems that appeared if using `SKIP_LOGIN = True` option without any multipass credentials in your `newdle.cfg`:
1. Couldn't sign in because I was getting redirected into `/login/newdle-sso` when trying to reach `/login/`, and newdle-sso would fail due to missing credentials
2. Couldn't sign out without getting flask error. This was simply because the logout endpoint had no logic reflecting `SKIP_LOGIN = True` option
N/A
- All tests pass ✅ 
- All linting rules pass ✅
Environment setup:
```
make
source ./.venv/bin/activate
make flask-server
make react-server
```
- `SKIP_LOGIN = True` on `newdle.cfg`
- No multipass credentials provided on `newdle.cfg`
1. I can sign in correctly into the test user ✅ 
2. I can sign out from the test user ✅ 
N/A
=> Fixing SKIP_LOGIN's logout and multipass redirects

newdle/api.py, newdle/client/src/answerSelectors.js, newdle/client/src/components/ParticipantTable.js, newdle/client/src/components/ParticipantTable.module.scss, newdle/client/src/components/answer/AnswerPage.js, newdle/client/src/components/answer/Calendar.js, newdle/client/src/components/answer/DayTimeline.js, newdle/client/src/components/answer/Option.js, newdle/client/src/components/answer/answer.module.scss, newdle/client/src/components/creation/timeslots/Timeline.js, newdle/client/src/selectors.js, newdle/client/src/util/date.js, newdle/core/util.py, requirements.txt
Adding timezone functionality to the newdle answer page as mentioned on #208 . The display timezone used by default is the one obtained from the user's browser. Dates are kept both in the format received by the server and in a timezone sensitive format to show the user
- Active date marked on calendar seems to ignore user timezone, need to look more into it
- All tests pass ✅ 
- All linting rules pass ✅
Environment setup:
```
make
source ./.venv/bin/activate
make flask-server
make react-server
```
- Newdle with same timezone as user's has it's dates displayed without changes ✅
- Newdle with option 17:00 - 17:30 on CEST displays as 12:00 - 12:30 on Sao Paulo time ✅
- Newdle displays date correctly with 12 hour difference (e.g. 10:00 August 31st on Japan should be 22:00 August 30th on Sao …
=> Displaying timezone on answers page

newdle/client/src/components/ParticipantTable.module.scss, newdle/client/src/components/creation/timeslots/Timeline.module.scss
closes #108
Now:
Also noticed a few misalignments in the `ParticipantTable`.
Before:
After:
=> Fix squeezed user avatars in timeline

newdle/client/src/client.js, newdle/client/src/components/ParticipantTable.js, newdle/client/src/components/ParticipantTable.module.scss, newdle/client/src/components/answer/AnswerPage.js, newdle/client/src/components/answer/answer.module.scss, newdle/migrations/versions/20200914_1149_679eab4aab01_add_comment_column_to_participants.py, newdle/models.py, newdle/schemas.py, tests/api_test.py
Closes #142 
A proposal for participant comments. 
These can easily be set, unset or replaced in the answers page.
=> Create a comments field for participants

setup.cfg, tests/api_test.py
Ensures that the given endpoint requires authentication.
The API should respond with `200` for valid auth and `401` when no auth is provided
=> Add 'get_busy_times' API test

newdle/client/src/components/creation/CreationHeader.js
I have not added the current user automatically as participant since it didn't seem necessary and, to me, it seemed to change the newdle creation flow significantly. Let me know if that is a desired feature which should be implemented.
=> Clarify invitation possibilities of participants

newdle/client/src/components/common/Calendar.js
Closes #251.
Since the datepicker does not yet allow switching the month from outside of the picker a rerender is necessary (see https://github.com/airbnb/react-dates/issues/1320).
=> Fix month switch when using arrows to navigate

newdle/client/src/components/creation/timeslots/DurationPicker.module.scss, newdle/client/src/components/creation/timeslots/Timeline.module.scss
The timezone label will now keep the same width and the text inside will be ellipsised accordingly. The 'Timezone' label does not jump to the bottom of the box anymore when typing in the box and no result is found.
=> Fix timezone dropdown for newdle creation

tests/api_test.py
The API should respond with 204 for a valid request and with 403 if the user is not the owner of the newdle. 404 check just in case.
=> Add 'send_result_emails' API test

setup.cfg, tests/emails/new-available-comment.txt, tests/emails/new-available-nocomment.txt, tests/emails/new-unavailable-comment.txt, tests/emails/new-unavailable-nocomment.txt, tests/emails/update-available-comment.txt, tests/emails/update-available-nocomment.txt, tests/emails/update-unavailable-comment.txt, tests/emails/update-unavailable-nocomment.txt, tests/notifications_test.py
It's very easy to get line breaks wrong in there, because generating plaintext emails is *nasty* as soon as there are any jinja constructs involved.
=> Add snapshot tests for plaintext emails

newdle/client/src/components/answer/Calendar.js, newdle/client/src/components/answer/DayTimeline.js, newdle/client/src/components/answer/answer.module.scss
This change makes the hours and answers columns with the same height, fixing the bottommost answers position. I used a header with a white space for having the same fixed-height elements in the hours and answers columns, but I'm not sure if it's the prettiest solution.
closes #221
=> Fix bottommost slots position in answer page (#221)

newdle/client/src/actions.js, newdle/client/src/answerSelectors.js, newdle/client/src/components/DayCarousel.js, newdle/client/src/components/answer/Calendar.js, newdle/client/src/components/answer/MonthCalendar.js, newdle/client/src/reducers/answer.js
Pressing the arrows will now change the active date without switching the whole view unless necessary.
Closes #254.
=> Change logic for arrows in answer view

newdle/client/src/components/NewdleTitle.js, newdle/client/src/locales/es/messages.po
Added <Trans> tag and `t` to template literal text.
closes #280
=> Add i18n capabilities to NewdleTitle component

newdle/client/src/components/creation/timeslots/TimeslotsStep.js, newdle/client/src/locales/es/messages.po
Closes #285 
I had to use Trans instead of Plural for numSlots as there was an html tag **strong** required for the numSlots value. 
Plural component's props _other_ takes in a string and if I pass in the **strong** tag, it renders as a string on the web page. I could have set a variable to JSX element with the **strong** tag and used that to render the _other_ prop using Plural, but I saw that the messages.po file picks up the variable name rather than the actual text. 
I tried multiple other variations but was unable to find a solution utilizing Plural.
=> Fixes #285-Add i18n: TimeslotsStep

README.md, newdle/api.py, newdle/client/package-lock.json, newdle/client/package.json, newdle/client/src/components/UserAvatar.js, newdle/client/src/components/creation/userSearch/UserSearch.js, newdle/client/src/components/creation/userSearch/UserSearch.module.scss, newdle/core/auth.py, newdle/core/util.py, newdle/schemas.py, newdle/templates/avatar.svg, tests/api_test.py
One thing to consider:
closes #139
=> Proxy gravatar requests via newdle

Makefile, newdle/client/.gitignore, newdle/client/package-lock.json, newdle/client/package.json, newdle/client/src/components/UserMenu.test.js, newdle/client/src/util/i18n.js
Note: Since the extension for the compiled files changed from .js to .mjs, delete the old ones manually (not sure if webpack prefers .js or .mjs if both exist): `rm newdle/client/src/locales/*/*.js`
=> Update to latest lingui version

Dockerfile
Related to #246
We can upgrade this to node 14, as we've been using it for quite some time now and the node-sass doesn't support it anymore (4.14+).
=> Update to nodejs 14

newdle/api.py, newdle/core/app.py, newdle/core/auth.py, newdle/core/util.py, newdle/newdle.cfg.example, newdle/schemas.py, tests/api_test.py
It's not a given that the auth provider will split "first" and "last" names. Moreover, there is no added value in having those in newdle. So, I suggest we just get rid of them.
=> Get rid of split names (first + last)

newdle/calendar.py
This PR changes the dates to UTC in the iCalendar files attached to participant emails to help outlook understand them correctly.
Closes https://github.com/indico/newdle/issues/350.
=> Fix timezone issues in outlook

newdle/client/src/components/summary/SummaryPage.js, newdle/client/src/locales/es/messages.po
This was only happening in `/newdle/:code/summary` (`<SummaryPage>` component), and not in `/newdle/:code/:partcode?` (`<AnswerPage>` component) as we thought initially.
Closes https://github.com/indico/newdle/issues/338.
=> Conditionally show delete button

newdle/client/src/components/summary/SummaryHeader.js
Closes #355
When a user visits a specific newdle (`/newdle/{code}/summary`), some data is automatically prefilled in the `creation`
redux state. If the user goes back to `/mine` and creates a new newdle, this data is not properly removed.
This PR adds a call to `abortCreation` when newdle summary is unmounted, which clears the state.
=> Fix previous newdle data leaking into newdle creation

newdle/newdle.cfg.example, newdle/providers/free_busy/ox.py
Closes #365 
OX cuts of the last day of the week instead of showing the full day until 23:59.
To get the data for the entire day, we request an extra week from OX.
With this change, we'll have to increment `OX_PROVIDER_MAX_WEEKS` in `newdle.cfg`.
=> Request an extra week of free-busy data with OX

newdle/client/src/components/GridCommon.js
Fixes a bug where the grid view in private newdles showed incorrect time ranges:
=> Take newdle duration from answerSelectors

newdle/client/src/components/NewdleTitle.js, newdle/client/src/components/NewdleTitle.module.scss, newdle/client/src/components/answer/AnswerHeader.js, newdle/client/src/components/answer/AnswerPage.js, newdle/client/src/components/summary/SummaryHeader.js, newdle/client/src/locales/es/messages.po
Closes #378
This PR makes the newdle's shareable link more prominent to avoid people copying the URL from the address bar.
=> Make it less likely for people to share their personal participant link

newdle/client/src/util/timezones.js
Closes #369 
The precompiled timezones did not take into account summer/winter time changes, always showing CEST.
This change adds ~20ms to the initial page load when the timezones have to be computed.
=> Generate timezones dynamically to reflect CET/CEST changes

newdle/client/src/components/App.js, newdle/client/src/components/MyNewdles.js, newdle/client/src/components/NewdleTitle.js, newdle/client/src/components/NewdlesParticipating.js, newdle/client/src/components/answer/AnswerHeader.js, newdle/client/src/components/creation/ClonePage.js, newdle/client/src/components/creation/CreationPage.js, newdle/client/src/components/creation/CreationSuccessPage.js, newdle/client/src/components/creation/EditPage.js, newdle/client/src/components/creation/FinalStep.js, newdle/client/src/components/creation/ParticipantsStep.js, newdle/client/src/components/creation/creation.module.scss, newdle/client/src/components/creation/index.js, newdle/client/src/components/creation/userSearch/UserSearch.js, newdle/client/src/components/summary/SummaryHeader.js, newdle/client/src/components/summary/SummaryPage.js, newdle/client/src/locales/es/messages.po
Adds a simple form where you can choose to keep participants and/or timeslots. You can also move the timeslots to some other date, that is, the timeslots will start on the selected date. This form then takes you to a prefilled newdle creation page where you can proceed as usual when creating a newdle.
=> Add option to clone newdles

newdle/client/src/components/creation/timeslots/Slot.js
This happens when the popup covers a part of the trigger when it renders which prevents the original hover event which hides the popup again and so on.
The problem here was the 'x' delete icon of the time slot which was being covered by the popup. The solution is to make only the slot itself as the trigger.
Another option would be to use the `hoverable` or `offset` props of SUI's <Popup />, but `hoverable` would not be that
user friendly since the tooltips are relatively large and cover other timeslots. `offset` would imo also look a bit weird since the offset would be need to be large to prevent the overlap.
=> Prevent popup from flickering when hovering a time slot

newdle/client/src/components/creation/timeslots/DurationPicker.js
From a SNOW ticket
- Increased maximum newdle duration from 8 -> 16 hours
- Small QoL change: hide the time picker and show the original dropdown once a custom duration is selected
=> Increase max newdle duration

newdle/client/package-lock.json, newdle/client/package.json, newdle/client/src/components/App.module.scss, newdle/client/src/components/DayCarousel.module.scss, newdle/client/src/components/Footer.module.scss, newdle/client/src/components/MyNewdles.module.scss, newdle/client/src/components/NewdleTitle.module.scss, newdle/client/src/components/TopHeader.module.scss, newdle/client/src/components/answer/answer.module.scss, newdle/client/src/components/common/FinalDate.module.scss, newdle/client/src/components/creation/CreationHeader.module.scss, newdle/client/src/components/creation/CreationSuccessPage.module.scss, newdle/client/src/components/creation/creation.module.scss, newdle/client/src/components/creation/timeslots/Timeline.module.scss, newdle/client/src/components/home/HomeHeader.module.scss, newdle/client/src/components/home/HomePage.module.scss, newdle/client/src/components/summary/summary.module.scss, newdle/client/src/styles/boxes.scss, newdle/client/src/styles/forms.scss
Based on [indico's migration from `node-sass` to `dart-sass`](https://github.com/indico/indico/pull/5734)
=> Switch to dart-sass

newdle/cli.py, newdle/newdle.cfg.example, newdle/providers/free_busy/util.py, requirements.in, requirements.txt
This allows using e.g. the redis backend which won't result in corruption when two request update the token at the exact same time.
=> Use flask-caching to store exchange token

newdle/client/src/components/creation/timeslots/CandidatePlaceholder.js, newdle/client/src/components/creation/timeslots/CandidateSlot.js, newdle/client/src/components/creation/timeslots/Timeline.js, newdle/client/src/components/creation/timeslots/Timeline.module.scss, newdle/client/src/locales/es/messages.po, newdle/client/src/util/date.js
This issue resolves #490. Continues #494 PR.
1. When the timeline is clicked, a new slot with the default duration is added.
2. A tooltip is displayed on mouse hover to indicate the position in the timeline.
3. The granularity is set to 15 minutes, but it can be changed using the time picker.
https://github.com/user-attachments/assets/263ae6a0-4d8d-40ec-9d65-cc7462481874
=> Use mouse click to add a new time slot

newdle/client/src/util/i18n.js
(I'll rebase the PO changes once the weblate stuff works)
Instead of only checking `navigator.language`, we use the BCP47 [matching algo](https://datatracker.ietf.org/doc/html/rfc4647#section-3.4) to find any matching locale in `navigator.languages`.
=> Add better locale detection
