indico/newdle

newdle/client/package-lock.json, newdle/client/package.json, newdle/client/src/App.js, newdle/client/src/App.module.scss, newdle/client/src/styles/palette.scss
=> Basic page structure

.editorconfig, newdle/api.py, newdle/auth.py, newdle/client/package-lock.json, newdle/client/package.json, newdle/client/src/App.js, newdle/client/src/App.test.js, newdle/client/src/AuthTest.js, newdle/client/src/actions.js, newdle/client/src/auth.js, newdle/client/src/client.js, newdle/client/src/index.js, newdle/client/src/reducers.js, newdle/client/src/selectors.js, newdle/client/src/setupProxy.js, newdle/client/src/store.js, newdle/core/app.py, newdle/core/auth.py, newdle/newdle.cfg.example, newdle/templates/login_result.html, requirements.txt
Also protect the API blueprint so it requires a token for all requests and add a client-side util that sends authenticated requests.
=> Integrate SSO

newdle/client/package-lock.json, newdle/client/package.json, newdle/client/src/App.js, newdle/client/src/App.module.scss, newdle/client/src/CreateNewdle.js, newdle/client/src/Home.js
=> Basic routing

.isort.cfg, newdle/api.py, newdle/client/src/client.js, newdle/core/app.py, newdle/core/webargs.py, newdle/schemas.py, requirements.txt
Return dummy data for now. Name and email should be enough - I don't think affiliation is needed here.
Example code I used to test it (no need for redux in the real user search code later, except when adding someone to the participants):
```diff
diff --git a/newdle/client/src/CreateNewdle.js b/newdle/client/src/CreateNewdle.js
index a1cc87e..c87bc0b 100644
--- a/newdle/client/src/CreateNewdle.js
+++ b/newdle/client/src/CreateNewdle.js
@@ -1,5 +1,36 @@
-import React from 'react';
+import React, {useState} from 'react';
+import {Input} from 'semantic-ui-react';
+import client from './client';
export default function CreateNewdle() {
-  return <h2>New newdle</h2>;
+  const [query, setQuery] = useState('');
+  const [searching, setSearching] = useState(false);
+
+  const handleSearch = async …
```
=> Add user search API

newdle/client/package-lock.json, newdle/client/package.json, newdle/client/src/Calendar.js, newdle/client/src/Calendar.module.scss, newdle/client/src/actions.js, newdle/client/src/reducers.js, newdle/client/src/selectors.js, newdle/client/src/util/date.js
=> Calendar component

newdle/client/src/App.js, newdle/client/src/CreateNewdle.js, newdle/client/src/CreateNewdle.module.scss, newdle/client/src/actions.js, newdle/client/src/components/Navigator.js, newdle/client/src/components/Timeline.module.scss, newdle/client/src/components/TopHeader.js, newdle/client/src/reducers.js, newdle/client/src/selectors.js
=> Add create newdle page layout

newdle/client/package-lock.json, newdle/client/package.json, newdle/client/src/CreateNewdle.js, newdle/client/src/actions.js, newdle/client/src/components/UserAvatar.js, newdle/client/src/components/UserMenu.js, newdle/client/src/components/UserSearch.js, newdle/client/src/components/UserSearch.module.scss, newdle/client/src/components/UserSearchForm.js, newdle/client/src/components/UserSearchResults.js, newdle/client/src/components/UserSearchResults.module.scss, newdle/client/src/reducers.js, newdle/client/src/selectors.js
=> User search

.travis.yml, Makefile, conftest.py, newdle/models.py, tests/models_test.py
=> Travis integration

newdle/client/src/App.js, newdle/client/src/Home.js
=> Keep anonymous users from creating newdles

newdle/client/src/CreateNewdle.js, newdle/client/src/TimelineExample.js, newdle/client/src/components/Participant.js, newdle/client/src/components/Timeline.js, newdle/client/src/components/Timeline.module.scss
=> Participant

newdle/client/src/actions.js, newdle/client/src/components/DurationPicker.js, newdle/client/src/components/DurationPicker.module.scss, newdle/client/src/components/Timeline.js, newdle/client/src/components/Timeline.module.scss, newdle/client/src/reducers.js, newdle/client/src/selectors.js
=> Add DurationPicker

newdle/api.py, newdle/models.py, newdle/newdle.cfg.example, newdle/schemas.py, tests/models_test.py
=> Add newdle codes

MANIFEST.in, Makefile, README.md, conftest.py, newdle/core/app.py, newdle/core/db.py, newdle/migrations/alembic.ini, newdle/migrations/env.py, newdle/migrations/script.py.mako, newdle/migrations/versions/20190828_1457_000000000000_create_initial_tables.py, requirements.txt
In the end I went straight for alembic since that way we easily get a clean DB for tests basically for free instead of having to manually delete all tables after the tests.
closes #38
=> Add DB cli

newdle/client/src/TimelineExample.js, newdle/client/src/components/Availability.js, newdle/client/src/components/CreateNewdle.js
=> Link calendar with the timeline

newdle/client/src/actions.js, newdle/client/src/client.js, newdle/client/src/components/CreateNewdle.js, newdle/client/src/components/CreateNewdle.module.scss, newdle/client/src/components/Navigator.js, newdle/client/src/reducers.js, newdle/client/src/selectors.js, newdle/client/src/styles/palette.scss
=> Final step

newdle/client/src/actions.js, newdle/client/src/components/App.js, newdle/client/src/components/CreateNewdle.js, newdle/client/src/components/CreateNewdle.module.scss, newdle/client/src/components/NewdleCreated.jsx, newdle/client/src/components/NewdleCreated.module.scss, newdle/client/src/reducers.js, newdle/client/src/selectors.js, newdle/client/src/util/router.js, newdle/core/app.py, newdle/schemas.py, tests/api_test.py
And redirect to a success page to avoid issues caused by the step etc. being reset
=> Clear creation state after creating a newdle

newdle/client/package-lock.json, newdle/client/package.json, newdle/client/src/actions.js, newdle/client/src/components/ParticipantTable.js, newdle/client/src/components/ParticipantTable.module.scss, newdle/client/src/reducers.js, newdle/client/src/selectors.js
=> Participant table

newdle/client/src/components/CandidateSlot.js, newdle/client/src/components/Slot.js, newdle/client/src/components/Timeline.js
=> Time slots improvements

newdle/client/src/components/Timeline.js
=> Fix slot rendering when end time > 24h

newdle/client/src/components/LazyDropdown.js, newdle/client/src/components/TimezonePicker.js
It takes quite long to render, and most people won't change its value, so now we just render some simple HTML and only turn it into a real dropdown when clicking it.
=> Make timezone selector dropdown lazy

newdle/client/src/components/App.js, newdle/client/src/components/MyNewdles.js, newdle/client/src/components/MyNewdles.module.scss
=> My newdles frontend

newdle/api.py, newdle/client/src/actions.js, newdle/client/src/client.js, newdle/client/src/components/Availability.js, newdle/client/src/components/PendingSlot.js, newdle/client/src/components/Timeline.js, newdle/client/src/components/Timeline.module.scss, newdle/client/src/components/TimelineRow.js, newdle/client/src/reducers/creation.js, newdle/client/src/selectors.js, newdle/client/src/styles/palette.scss, newdle/core/util.py, newdle/schemas.py
The server can return dummy data for now since we don't have access to an API yet that gives us real data.
=> Get participant availability using the API

newdle/client/src/components/creation/FinalStep.js, newdle/client/src/components/creation/creation.module.scss, newdle/client/src/components/creation/timeslots/Calendar.js, newdle/client/src/components/creation/timeslots/Calendar.module.scss, newdle/client/src/components/creation/timeslots/TimeslotsStep.js
As discussed on Mattermost.
Closes #79
=> Step 2: add number of slots indicator

newdle/client/src/actions.js, newdle/client/src/answerSelectors.js, newdle/client/src/components/App.js, newdle/client/src/components/TopHeader.js, newdle/client/src/components/answer/AnswerHeader.js, newdle/client/src/components/answer/AnswerPage.js, newdle/client/src/components/answer/Calendar.js, newdle/client/src/components/answer/MonthCalendar.js, newdle/client/src/components/creation/timeslots/Timeline.js, newdle/client/src/reducers/answer.js, newdle/client/src/selectors.js
Also use the correct URL with the newdle and participant code.
=> Answer page: Fetch Newdle details from server

newdle/client/src/actions.js, newdle/client/src/answerSelectors.js, newdle/client/src/components/answer/AnswerPage.js, newdle/client/src/components/answer/Calendar.js, newdle/client/src/reducers/answer.js, newdle/client/src/util/date.js
Currently using dummy availability data.
closes #82
=> Make 'accept all available slots' switch functional

newdle/client/src/components/DayCarousel.js, newdle/client/src/components/DayCarousel.module.scss, newdle/client/src/components/answer/Calendar.js
=> Day transitions

newdle/api.py, newdle/client/src/answerSelectors.js, newdle/client/src/client.js, newdle/client/src/components/App.js, newdle/client/src/components/TopHeader.js, newdle/client/src/components/answer/AnswerPage.js, newdle/client/src/components/answer/answer.module.scss, newdle/client/src/components/creation/FinalStep.js, newdle/client/src/components/creation/creation.module.scss, newdle/client/src/components/home/HomePage.module.scss, newdle/client/src/styles/boxes.scss, newdle/client/src/styles/forms.scss, newdle/schemas.py, tests/api_test.py
=> Add anonymous participants

newdle/client/src/components/DayCarousel.js, newdle/client/src/components/answer/Calendar.js, newdle/client/src/components/answer/DayTimeline.js, newdle/client/src/components/answer/MultipleSlot.js, newdle/client/src/components/answer/Option.js, newdle/client/src/components/answer/Slot.js, newdle/client/src/components/answer/answer.module.scss, newdle/client/src/components/creation/timeslots/Timeline.js, newdle/client/src/components/creation/timeslots/TimelineHeader.js, newdle/client/src/util/date.js
=> Style fixes

newdle/api.py, newdle/client/src/actions.js, newdle/client/src/answerSelectors.js, newdle/client/src/components/answer/AnswerHeader.js, newdle/client/src/components/answer/AnswerPage.js, newdle/client/src/components/answer/Calendar.js, newdle/client/src/components/answer/DayTimeline.js, newdle/client/src/components/answer/Slot.js, newdle/client/src/components/creation/timeslots/Availability.js, newdle/client/src/reducers/answer.js
=> Fetch and display busy times on answer page

newdle/api.py, newdle/cern_integration.py, newdle/core/app.py, newdle/core/cache.py, newdle/newdle.cfg.example, newdle/oauth_util.py, requirements.txt
=> Search for real CERN users

newdle/client/src/answerSelectors.js, newdle/client/src/components/answer/AnswerPage.js, newdle/client/src/components/answer/answer.module.scss
=> Add participant name when answering

.gitattributes, newdle/api.py, newdle/client/src/components/creation/CreationSuccessPage.js, newdle/client/src/components/creation/FinalStep.js, newdle/core/app.py, newdle/core/util.py, newdle/newdle.cfg.example, newdle/notifications.py, newdle/templates/invitation_email.html, newdle/templates/invitation_email.txt, newdle/vendor/django_mail/__init__.py, newdle/vendor/django_mail/backends/base.py, newdle/vendor/django_mail/backends/console.py, newdle/vendor/django_mail/backends/locmem.py, newdle/vendor/django_mail/backends/smtp.py, newdle/vendor/django_mail/encoding_utils.py, newdle/vendor/django_mail/mail_utils.py, newdle/vendor/django_mail/message.py, newdle/vendor/django_mail/module_loading_utils.py
=> Send email to participants on newdle creation

newdle/api.py, newdle/client/src/actions.js, newdle/client/src/answerSelectors.js, newdle/client/src/client.js, newdle/client/src/components/answer/AnswerPage.js, newdle/client/src/components/answer/DayTimeline.js, newdle/client/src/components/answer/Slot.js, newdle/client/src/components/answer/answer.module.scss, newdle/client/src/components/creation/timeslots/Slot.js, newdle/client/src/components/creation/timeslots/Timeline.module.scss, newdle/client/src/components/creation/timeslots/TimelineRow.js, newdle/client/src/reducers/creation.js, newdle/core/util.py, newdle/newdle.cfg.example, newdle/providers/free_busy/exchange.py, newdle/providers/free_busy/random.py, setup.py
We should see whether `providers/free_busy` is the right place where to have this. I think we could probably group the free/busy "plugins" with the specific authentication ones...
Closes #106
=> Add Exchange free/busy provider

newdle/api.py, newdle/client/src/components/answer/AnswerPage.js, newdle/client/src/components/common/FinalDate.js, newdle/client/src/components/common/FinalDate.module.scss, newdle/client/src/components/summary/SummaryPage.js, newdle/client/src/components/summary/summary.module.scss
Closes #111 
Answer page:
Changed on summary page as well:
=> Block answering when newdle is finished

newdle/api.py, newdle/client/src/actions.js, newdle/client/src/answerSelectors.js, newdle/client/src/client.js, newdle/client/src/components/answer/AnswerPage.js
only allow it for participants of a given newdle to avoid opening this API to anyone who can access newdle
=> Allow busy check w/o token

newdle/api.py, newdle/client/src/actions.js, newdle/client/src/answerSelectors.js, newdle/client/src/client.js, newdle/client/src/components/answer/AnswerPage.js, newdle/client/src/components/answer/answer.module.scss, newdle/client/src/reducers/answer.js
=> Answer Page UI

newdle/api.py, newdle/client/src/client.js, newdle/client/src/components/summary/SummaryPage.js, newdle/client/src/components/summary/summary.module.scss, newdle/client/src/selectors.js, newdle/client/src/styles/palette.scss, newdle/templates/result_email.html, newdle/templates/result_email.txt
=> Send summary e-mails

newdle/client/src/components/creation/FinalStep.js, newdle/schemas.py
=> Newdle title cannot be more than 80 chars

Makefile, README.md, conftest.py, newdle/api.py, newdle/client/src/answerSelectors.js, newdle/client/src/client.js, newdle/client/src/components/UserMenu.js, newdle/client/src/components/UserMenu.module.scss, newdle/client/src/components/answer/AnswerPage.js, newdle/client/src/selectors.js, newdle/core/util.py, newdle/schemas.py, newdle/vendor/django_mail/__init__.py, package.json, requirements.dev.txt, setup.cfg, tests/api_test.py, tests/models_test.py, tests/util_test.py
Also took the occasion to rename "anonymous participant" -> "unknown participant", since those participants do have name anyway.
Closes #115
=> Add user data signatures

newdle/api.py, newdle/client/src/actions.js, newdle/client/src/client.js, newdle/client/src/components/App.js, newdle/client/src/components/ErrorMessage.js, newdle/client/src/components/ErrorMessage.module.scss, newdle/client/src/components/MyNewdles.js, newdle/client/src/components/UserAvatar.js, newdle/client/src/components/answer/AnswerPage.js, newdle/client/src/components/creation/FinalStep.js, newdle/client/src/components/creation/userSearch/UserSearch.js, newdle/client/src/components/summary/SummaryPage.js, newdle/client/src/reducers/index.js, newdle/client/src/selectors.js, tests/api_test.py
=> Error handling

newdle/client/src/components/TopHeader.js, newdle/client/src/components/TopHeader.module.scss, newdle/client/src/components/home/HomePage.js, newdle/client/src/components/home/HomePage.module.scss
=> Fix elements responsiveness in home page

newdle/client/src/components/creation/CreationSuccessPage.js, newdle/client/src/components/creation/CreationSuccessPage.module.scss
Closes #132 
Copy to Clipboard Button added using clipboard API.
=> Add copy to clipboard btn in creation success page

README.md
Added a GIF into the README 
https://github.com/indico/newdle/issues/137
=> Add Preview GIF to README

newdle/client/src/components/MyNewdles.js, newdle/client/src/components/MyNewdles.module.scss
Display create first newdle screen on my newdle screen if no newdles - closes #145
=> Display create first newdle screen on my newdle screen if no newdles

newdle/client/src/components/MyNewdles.js, newdle/client/src/components/answer/AnswerPage.js, newdle/client/src/components/creation/CreationPage.js, newdle/client/src/components/creation/CreationSuccessPage.js, newdle/client/src/components/summary/SummaryPage.js, newdle/client/src/util/hooks.js, newdle/templates/login_result.html
=> Use more detailed page titles

newdle/client/src/components/AvailabilityRing.js, newdle/client/src/components/ParticipantTable.js, newdle/client/src/selectors.js
It's quite annoying to not see whether people are actually unavailable or just haven't answered yet.
=> Use gray availability ring segment for "unanswered"

newdle/client/src/components/UserMenu.js, newdle/client/src/components/UserMenu.module.scss
- Fixes #193
- Replace `<span>` with `<a>` in UserMenu.js
- Add CSS for the appropriate class in UserMenu.module.scss
Signed-off-by: Achintya Rao <achintya.rao@cern.ch>
=> Make login link “clickable” by keyboard shortcuts

.travis.yml, newdle/client/src/components/ParticipantTable.js, newdle/client/src/components/ParticipantTable.module.scss, newdle/client/src/components/summary/SummaryPage.js, newdle/client/src/components/summary/summary.module.scss, newdle/client/src/selectors.js
=> Display more information in finalized newdle

newdle/client/package-lock.json, newdle/client/package.json, newdle/client/src/components/creation/timeslots/Timeline.js, newdle/client/src/components/creation/timeslots/Timeline.module.scss
=> Use rc-time-picker for timeslot selection

newdle/client/src/components/ParticipantTable.js, newdle/client/src/components/ParticipantTable.module.scss, newdle/client/src/selectors.js
=> Show list of participants in summary

newdle/client/src/components/ParticipantTable.js, newdle/client/src/components/summary/SummaryPage.js, newdle/client/src/components/summary/summary.module.scss, newdle/client/src/selectors.js, newdle/schemas.py, tests/api_test.py
=> Display participants who have not voted yet in summary

newdle/client/package-lock.json, newdle/client/package.json, newdle/client/src/components/App.module.scss, newdle/client/src/components/DayCarousel.module.scss, newdle/client/src/components/TopHeader.module.scss, newdle/client/src/components/answer/AnswerPage.js, newdle/client/src/components/answer/Calendar.js, newdle/client/src/components/answer/answer.module.scss, newdle/client/src/components/common/Calendar.js, newdle/client/src/components/common/Calendar.module.scss, newdle/client/src/util/hooks.js
=> Make answer page responsive

newdle/client/src/components/creation/timeslots/CandidateSlot.js, newdle/client/src/components/creation/timeslots/DurationPicker.js, newdle/client/src/components/creation/timeslots/DurationPicker.module.scss, newdle/client/src/components/creation/timeslots/Timeline.module.scss
=> Add a custom duration picker

.travis.yml, Makefile, README.md, package.json, pyproject.toml
Unused imports etc are just warnings and are easily missed atm
=> Fail CI on eslint warnings & use latest python/postgres

newdle/client/src/components/ParticipantTable.js, newdle/client/src/components/ParticipantTable.module.scss, newdle/client/src/components/summary/SummaryPage.js, newdle/client/src/util/hooks.js
=> Make ParticipantTable responsive

.github/workflows/ci.yml, conftest.py
=> Add Github actions for CI 

Makefile, newdle/api.py, newdle/calendar.py, newdle/notifications.py, setup.cfg
Closes #143 .
I tested it out with gmail and it seems to parse the information properly.
This is the generated ICS file for the above, in case you want to take a look:
```
BEGIN:VCALENDAR
BEGIN:VEVENT
SUMMARY:Something like this
DTSTART;TZID=Europe/Paris;VALUE=DATE-TIME:20200914T110000
DTEND;TZID=Europe/Paris;VALUE=DATE-TIME:20200914T113000
DTSTAMP;VALUE=DATE-TIME:20200914T130547Z
ORGANIZER;CN="Cristi Sch":MAILTO:REDACTED
END:VEVENT
END:VCALENDAR
```
=> Attach icalendar invite for participants

newdle/client/src/components/UserAvatar.js, newdle/client/src/components/common/Calendar.module.scss, newdle/client/src/components/creation/timeslots/Timeline.js, newdle/client/src/components/creation/timeslots/Timeline.module.scss, newdle/client/src/components/creation/timeslots/TimelineRow.js, newdle/client/src/components/creation/timeslots/TimeslotsStep.js
Changed the layout of TimeslotStep and Timeline components to be responsive and mobile/tablet friendly
=> Mobile timeline

newdle/client/src/actions.js, newdle/client/src/answerSelectors.js, newdle/client/src/components/answer/AnswerPage.js, newdle/client/src/components/answer/Calendar.js, newdle/client/src/components/answer/answer.module.scss, newdle/client/src/components/common/TimezonePicker.js, newdle/client/src/components/common/TimezonePicker.module.scss, newdle/client/src/components/creation/timeslots/Timeline.js, newdle/client/src/images/timezone.svg, newdle/client/src/reducers/answer.js, newdle/client/src/selectors.js, newdle/client/src/styles/palette.scss, newdle/client/src/util/date.js
=> Allow changing displayed timezone on answer page

newdle/client/package-lock.json, newdle/client/package.json, newdle/client/src/components/DayCarousel.module.scss, newdle/client/src/components/answer/Calendar.js, newdle/client/src/components/answer/DayTimeline.js, newdle/client/src/components/answer/answer.module.scss, newdle/client/src/styles/palette.scss, newdle/client/src/util/hooks.js
closes #158 
This change indicates on the right side the day that has been selected in the Month Calendar.
=> [Answers] Highlight selected day

.github/workflows/ci.yml
=> CI action: Run linters only once

.editorconfig, .github/workflows/migration-sql.yml, Makefile, ci/check_history_consistency.py, ci/print_revision_sql.sh, package.json
Fixes #238 
See the workflow in action in the following PR on my local fork: https://github.com/saibot94/newdle/pull/2
=> SQL Migrations printer

newdle/api.py, newdle/cli.py, newdle/client/src/client.js, newdle/client/src/components/NewdleTitle.js, newdle/client/src/components/answer/AnswerHeader.js, newdle/client/src/components/answer/AnswerPage.js, newdle/client/src/components/summary/SummaryHeader.js, newdle/client/src/components/summary/SummaryPage.js, newdle/client/src/components/summary/summary.module.scss, newdle/migrations/versions/20200928_1154_d85e02075214_add_newdle_deletion_date.py, newdle/models.py, newdle/newdle.cfg.example, newdle/schemas.py, newdle/templates/deletion_email.html, newdle/templates/deletion_email.txt, tests/api_test.py, tests/cli_test.py, tests/emails/deletion-comment.txt, tests/emails/deletion-nocomment.txt, tests/notifications_test.py
=> Allow creator to delete a newdle

newdle/client/src/components/TopHeader.js, newdle/client/src/components/UnloadPrompt.js, newdle/client/src/locales/es/messages.po
Closes #286 & closes #287 
Lemme know if anything needs to changed.
Thank you!
=> Added i18n for UnloadPrompt and TopHeader

newdle/client/src/components/creation/userSearch/UserSearchResults.js, newdle/client/src/locales/es/messages.po
Closes #291 
I only found one thing needed to be translated in this file. Let me know if I missed anything. Thanks!
=> Added i18n for UserSearchResults

newdle/client/src/components/ErrorMessage.js, newdle/client/src/components/creation/CreationSuccessPage.js, newdle/client/src/components/login/LoggingIn.js, newdle/client/src/locales/es/messages.po
Closes #272 , Closes #276 , Closes #271
=> Add i18n to ErrorMessage.js LoggingIn.js CreationSucessPage.js

newdle/client/src/components/UserMenu.js, newdle/client/src/components/UserMenu.test.js, newdle/client/src/locales/es/messages.po
Close #288. Let me know if there is something missing!
=> Added i18n for UserMenu

newdle/client/src/components/creation/ParticipantsStep.js, newdle/client/src/locales/es/messages.po
=> add i18n for participants step

newdle/client/src/components/common/FinalDate.js, newdle/client/src/components/login/LoginPrompt.js, newdle/client/src/locales/es/messages.po
=> Add i18n for LoginPrompt and FinalDate

newdle/client/src/components/common/TimezonePicker.js, newdle/client/src/components/creation/timeslots/DurationPicker.js, newdle/client/src/locales/es/messages.po
Added i18n for the two components - TimezonePicker and DurationPicker. I separated from the issue #284.
=> i18n: DurationPicker

newdle/client/src/components/creation/userSearch/UserSearch.js, newdle/client/src/locales/es/messages.po
=> Added i18n: UserSearch #289

newdle/client/src/components/common/LanguageSelector.js, newdle/client/src/locales/es/messages.po
Add `t` to placeholder test in LanguageSelector component
closes #275
=> Added i18n-capabilities to LanguageSelector component

newdle/client/src/components/answer/Calendar.js, newdle/client/src/components/creation/FinalStep.js, newdle/client/src/locales/es/messages.po
=> Add i18n to FinalStep & Calendar

newdle/client/src/components/NewdlesParticipating.js, newdle/client/src/locales/es/messages.po
Added `<Trans>` `<Plural>` and `t` to text fields in NewdlesParticpating component to provide i18n capabilities. Tested `<Plural>` on Chrome browser in Spanish.
=> I18n newdles participating

newdle/client/src/components/ParticipantTable.js, newdle/client/src/locales/es/messages.po
Added `t` and `Plural` where needed to provide i18n capabilities to the ParticpantTable component.
=> Add i18n capabilities to ParticipantTable component

newdle/client/src/components/creation/userSearch/UserSearchForm.js, newdle/client/src/locales/es/messages.po
=> Fixes issue #290 - Add i18n: UserSearchForm

newdle/client/src/components/creation/CreationHeader.js, newdle/client/src/locales/es/messages.po
=> Update CreationHeader.js with i18n

newdle/client/src/components/UserAvatar.js, newdle/client/src/components/UserMenu.test.js, newdle/schemas.py, tests/api_test.py
Derive the initials from the participant name instead of serving it from the server-side.
=> Move the initials to the client side

newdle/client/src/components/creation/userSearch/UserSearchResults.js, newdle/client/src/components/creation/userSearch/UserSearchResults.module.scss, newdle/client/src/locales/es/messages.po
=> Show avatar in user search results

newdle/api.py, newdle/client/src/components/answer/AnswerPage.js, newdle/client/src/components/answer/answer.module.scss, newdle/core/util.py, newdle/schemas.py, tests/api_test.py
This also gives participants without email address a user avatar depending on their name.
=> Show avatar on answer page

.github/workflows/ci.yml, .github/workflows/migration-sql.yml
=> Stop using deprecated APIs in GitHub actions

newdle/client/src/components/MyNewdles.js, newdle/client/src/locales/es/messages.po
=> Add i18n for MyNewdles

newdle/client/src/reducers/creation.js
Now it works for both existing and new participants
=> Fix removing participants

docker-compose.development.yml
The messages.po file was not generated and the whole dev testing malfunctioned as described in #340, this addition fixes it (same is running make i18n), thanks @ThiefMaster!
=> Fixed #340

newdle/client/src/components/summary/SummaryPage.js
Following up on #343 and other similar complaints, and since Indico 3.0 and consequent API availability is still weeks away.
=> Temporarily comment "create event" button

newdle/api.py, newdle/client/src/client.js, newdle/client/src/components/summary/SummaryPage.js, newdle/client/src/locales/es/messages.po, newdle/newdle.cfg.example
closes #128
Corresponding PR in Indico: https://github.com/indico/indico/pull/4628
=> Call Indico API for event creation

newdle/api.py, newdle/client/src/actions.js, newdle/client/src/client.js, newdle/newdle.cfg.example, newdle/providers/free_busy/exchange.py, newdle/providers/free_busy/ox.py, tests/api_test.py
Closes https://github.com/indico/newdle/issues/349.
=> Add free-busy interface for CERN OX client

newdle/api.py, newdle/client/src/components/App.js, newdle/client/src/components/App.module.scss, newdle/migrations/versions/20210531_1656_28103ebec68e_add_stats_table.py, newdle/models.py, newdle/providers/free_busy/random.py, tests/api_test.py
With the auto-deletion feature we'd otherwise lose information on how many newdles have been created since the beginning.
Also fixed some small bugs (broken random free-busy, and an invalid html tag).
=> Keep persistent stats

newdle/providers/free_busy/exchange.py
Closes https://github.com/indico/newdle/issues/359.
=> Fail gracefully for Exchange users who made their free/busy info private

newdle/templates/invitation_email.html, newdle/templates/invitation_email.txt, tests/emails/invitation.txt, tests/notifications_test.py
=> Reword emails to avoid unnecessary pronoun usage

newdle/client/src/components/ParticipantGrid.js, newdle/client/src/components/ParticipantGrid.module.scss, newdle/client/src/components/ParticipantTable.module.scss, newdle/client/src/components/summary/SummaryPage.js, newdle/client/src/components/summary/summary.module.scss, newdle/client/src/locales/es/messages.po
=> Results overview

newdle/client/src/components/creation/userSearch/UserSearch.js, newdle/client/src/locales/es/messages.po
=> Add 'Add myself' option to participant search

newdle/schemas.py, tests/api_test.py
Fixes missing signature when using `Add myself`
=> Add signature to UserSchema

newdle/providers/free_busy/exchange.py, setup.cfg
Also pinned exchangelib's version.
=> Remove calls to exchangelib deprecated method

newdle/client/src/answerSelectors.js
=> Fix equality comparison of participant answers

newdle/client/src/components/answer/AnswerPage.js, newdle/client/src/components/answer/answer.module.scss, newdle/client/src/components/common/TimezonePicker.module.scss, newdle/client/src/components/creation/userSearch/UserSearch.js, newdle/client/src/components/creation/userSearch/UserSearch.module.scss, newdle/client/src/locales/es/messages.po
Some smaller improvements to the mobile view:
- Adds tabs for the calendar and timeline
- Centers timezone dropdown menu so it does not clip on small screens
- Smooth scroll up after submitting an answer to see the success message
=> Improve mobile view

newdle/client/src/components/creation/FinalStep.js, newdle/client/src/components/creation/creation.module.scss, newdle/client/src/locales/es/messages.po
**Standard view:**
**Mobile view:**
=> Make newdle type selection clearer

newdle/client/src/components/summary/SummaryPage.js, newdle/client/src/components/summary/summary.module.scss, newdle/client/src/locales/es/messages.po
=> Allow exporting to csv/excel before finalizing newdle

newdle/client/src/components/answer/Calendar.js, newdle/client/src/util/date.js
=> Fix rendering of timeslots spanning two days

newdle/core/webargs.py
Spotted while working on #450.
=> Fix a typo in the name of the class

newdle/client/src/components/MyNewdles.js, newdle/client/src/components/creation/timeslots/DurationPicker.js, newdle/client/src/locales/it/messages.po
as discussed in #503 i added the italian .po file, also i found a couple of missing t tags
=> IT translation and missing translation tags

newdle/client/src/components/common/LanguageSelector.js, newdle/client/src/components/common/LanguageSelector.module.scss, newdle/client/src/util/i18n.js
=> Enable the language selector
